export const ENV_KEYS = {
  MONGO_URI: 'MONGO_URI',
  PORT: 'PORT',
  CHECKOUT_PERIOD: 'CHECKOUT_PERIOD',
  MAX_CHECKOUTS: 'MAX_CHECKOUTS',
  ALLOW_SIMULTANEOUS_CHECKOUTS: 'ALLOW_SIMULTANEOUS_CHECKOUTS',
  CHECKOUT_FEATURE: 'CHECKOUT_FEATURE',
  RETURN_FEATURE: 'RETURN_FEATURE',
  ADD_BOOK_FEATURE: 'ADD_BOOK_FEATURE',
};
